# Machine Learning {#sec-02-MachineLearning}

> "Human beings are not just passive victims of disease. They are active participants in the biological confrontation between man and microbe."

## Overview

This chapter provides a simple explanation of how to model fast-growing phenomena, such as the spread of infectious diseases. Conversely, it also look at how a rapidly growing health impact can influence the health metrics of certain countries without significantly affecting the global perspective. More specifically, a further look will be provided at the evolution of the infection in some specific countries, and how this influences the overall level of health metrics.

The spread of a virus can be seen as a **random process**, since the number of individuals who are infected at any given time can change randomly. The exact number of individuals who will be infected in the future cannot be determined with certainty, as it depends on various factors such as the contagiousness of the virus, the behavior of individuals, and the efficacy of mitigation measures.

A **deterministic model**, on the other hand, could be used to model the spread of a virus under certain conditions, such as a fixed number of individuals, constant contagiousness, and no mitigation measures. This type of model can be used to make predictions about the spread of a virus under certain assumptions, but it will not account for the randomness and uncertainty associated with real-world scenarios.

In general, a **stochastic process**, or random process [@dobrow2016] is the type of model which attempt to replicate uncertain outcomes. At opposite, in a **deterministic system** the outcome is obtained from a given input, and for this reason it is reproducible.

Most models used to study the spread of a virus are a **combination of both deterministic and stochastic models**. For example, the SIR (Susceptible-Infected-Recovered) model is a deterministic model that describes the dynamics of the spread of a virus, but it also includes stochastic elements such as random interactions between individuals.

The emergence of infections is an ongoing evolution and adaptation[@broemeling2021], and to use the words of one of the most popular involved with the study of the state of health, yet in the late 1970s, Dubos' believed that "the relationship between humans and microbes is dynamic and influenced by various factors, including environmental conditions, human behavior, and microbial adaptation". He highlighted the importance of understanding the complex interactions between host and pathogen in the emergence and spread of infectious diseases. As microbiologist, *René Dubos* described life as a dynamic interplay between organisms and their environment, as a **process of adaptation and interaction**, where organisms continuously respond to changes in their surroundings to maintain balance and survival. This is the exact explanation of what happens inside a machine learning model environment. A continuous parameters learning and adjustment process due to simulations of the observed data.

### Best practices for application of machine learning models

1.  Data checking

-   do research on the topic
-   identify data sources
-   create a data dictionary

2.  Exploratory Data Analysis

-   visualize the relationship between the response and predictor

3.  Feature Engineering

-   consider transforming variables to a standard format

4.  Modelling Decision

-   decide for the model that best suits your data
-   simulate different scenarios
-   apply learning parameters to your model

## Measures of Machine Learning Models

> The loss function is **a method for evaluating how well a machine learning algorithm models featured a data set**[^02-machinelearning-1]. The ***cost function*** is the average of all loss function values.

[^02-machinelearning-1]: <https://builtin.com/machine-learning/common-loss-functions>

### Loss functions based on modeling techniques

Modeling techniques are Regression and Classification modeling, this is depending on whether the output or the reference variable of the analysis is numeric or categorical, respectively.

-   Regression:

    -   Mean Square Error / Quadratic Loss / L2 Loss

        $$
        MSE=\frac{1}{n}\sum_{i=1}^{n}{(\hat{}Y_i-Y_i)^2}
        $$

    -   Mean Absolute Error / L1 Loss

        $$
        MAE=\frac{\sum_{i=1}^{n}{|y_i-x_i|}}{n}
        $$

    -   Huber Loss / Smooth Mean Absolute Error

        $$
        L_{\delta}(y,f(x))=\left\{\begin{matrix} \frac{1}{2}(y-f(x))^2 & \text{for } |y-f(x)|\leq \delta, \\ \delta|y-f(x)|-\frac{1}{2}\delta^2 & \text{otherwise.} \end{matrix}\right.
        $$

    -   Log-Cosh Loss

    -   Quantile Loss

-   Classification:

    -   Binary Cross-Entropy Loss / Log Loss

        $$
        L=-\frac{1}{m}\sum_{i=1}^{m}{(y_i*log(\hat{y_i})+(1-y)log(1-\hat{y}))}
        $$

    -   Hinge Loss

        $$
        L=max(0,1-y*f(x))
        $$

### Public health loss functions

> "The public may be less interested in environmental quality than in economic prosperity." Dubos

In the field of public health the measures of cost like mortality and morbidity are used to evaluate the outcome of health and well-being of a population.

The most common analyses methods are[@hult2021]:

-   cost-utility, using quality-adjusted life years (QALY)

-   cost-effectiveness, for specific outcomes, such as life expectancy or medical outcomes.

As mentioned in the history of health metrics, a cost-utility framework is one used for the calculation of QALY, a measure that within time has been considered as discriminating disabilities in the population by assessing a cost which was too higher or too low in most of the situation and was largely criticized for not being able to capture the whole picture.

Comprehensive tools assessing the impacts through cost-effectiveness measures to estimate the effectiveness of health interventions should also include a measure of disability. The measure of DALY (1993) developed for major consideration of the disability status for the evaluation of the well-being of a population was then built adding a further layer based on weights of disability.

So, to recap, the measures for a cost-effectiveness intervention are:

-   mortality
-   morbidity
-   disability
