# Introduction to Data Visualizaion {#sec-09-data_visualization}

```{r}
#| echo: false
library(tidyverse)
#source("R/_common.R")
```

## Overview

One of my favorite topics to practice with for understanding more about
data to be analysed is visualization. Through visualizing data we can
summarize the information contained in it, tell a story about the
interaction of key variables in the data, represent statistical values
and finally design the background of the story.

If you'd like to practice making data visualization there many
free-available channels that allow you to gain information on how to do
it as well as improve abilities by practicing and sharing final results.
Received feed-back might be harsh, world is bad, you may feel sick but
you'll get better is you don't give up.

Taking part to competions such as #TidyTuesday #30DayCharChallenge, even
practicing making map, that we will see more closely in the Spatial
chapter of this book will help getting better. At some point you'll feel
healthy!

### History of Data Visualization

The history of data visualization spans over centuries, the roots of
data visualization can be traced back to ancient times with rudimentary
visual representations, its modern form began to take shape with the
growth of statistics and graphical methods in the 17th and 18th
centuries. One notable milestone was the publication of *William
Playfair*'s "Commercial and Political Atlas" in 1786, which introduced
innovative graphical techniques like the line graph, bar chart, and pie
chart. Throughout the 19th and 20th centuries, pioneers such as
*Florence Nightingale*, *John Snow*, and *Jacques Bertin* further
advanced the field, using visualizations to communicate complex data and
uncover insights.

The digital revolution of the late 20th century with the advent of
powerful computing technologies enabled the creation of interactive and
dynamic visualizations. Today, data visualization plays a crucial role
in fields of Data Science from business analytics and scientific
research to journalism and public policy, serving as a potent tool for
summarising, communicating, and interpreting data.

### The Grammar of Graphics

The `plot()` function and its competitor `ggplot()` are tools.

### Colors and Palette

### Legend and Giudes

### Plots layouts

### Saving as an Image
