project:
  type: book
  output-dir: _book

book:
  title: "Health Metrics and the Spread of Infectious Diseases"
  subtitle: "Machine Learning Applications and Spatial Modelling Analysis with R"
  #abstract: "A walk through a comprehensive exploration of health metrics, their calculation, modeling, and cross-country comparisons. This book spans the intricate landscape of public health analysis, offering a practical examination of various methodologies and approaches. From the fundamentals of health metrics calculation to providing an overview of modeling techniques, it equips readers with the knowledge and tools essential for understanding and interpreting health data, gaining valuable insights into global disparities and factors influencing health outcomes. In addition to providing the R code necessary to produce the analysis, the book teaches how to create appropriate data visualizations and maps. In compliance with the principles of transparency and reproducibility, all datasets utilized in this book have been organized into an R package called [{hmsidwR}](https://fgazzelloni.github.io/hmsidwR/). This integration ensures that readers have easy access to the necessary data, thereby facilitating the replication of the analyses presented throughout the text."
  author:
    name: Federica Gazzelloni
    orcid: 0000-0002-4285-611X
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-J9YVQPL7W9"
    anonymize-ip: true
  site-url: https://fgazzelloni.quarto.pub/hmsidr/
  repo-url: https://github.com/Fgazzelloni/hmsidR
  repo-branch: origin
  sharing: [twitter, facebook, linkedin]
  publisher: "CRC Press - Chapman & Hall"
  publisher-place: "Boca Raton, FL."
  repo-actions: [edit, issue]
  cover-image: images/cover.png
  favicon: images/cover.png
  date: "06/09/2023" # date of the aggrement with the Editor
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    foreground: "primary"
    background: "#ebecf7"
    pinned: true
    style: docked

  page-footer:
    left: |
      &copy; 2024 This book is written by <a href="https://federicagazzelloni.netlify.app/">Federica Gazzelloni</a>.
    center: |
      Editor CRC Press - Chapman & Hall | Taylor & Francis Group
    right: |
      Built with ❤︎️ and [Quarto](https://quarto.org/)
    background: "#29306c"

  chapters:
    - index.qmd
    - intro.qmd
    - part: "**Health Metrics**"
      chapters:
        - 01-health_metrics.qmd
        - 02-method_calculation.qmd
        - 03-components.qmd
        - 04-causes_risks.qmd
    - part: "**Machine Learning**"
      chapters:
        - 05-machine_learning.qmd
        - 06-techniques.qmd
        - 07-packages.qmd
        - 08-predictions.qmd
    - part: "**Data Visualization**"
      chapters:
        - 09-data_visualization.qmd
        - 10-applications.qmd
        - 11-spatials.qmd
        - 12-examples.qmd
    - part: "**Infectious Diseases**"
      chapters:
        - 13-infectious_diseases.qmd
        - 14-covid19.qmd
        - 15-malaria.qmd
        - 16-summary.qmd
    - conclusions.qmd
    - references.qmd
    - formulary.qmd
  appendices:
    - appendixA.qmd
    - appendixB.qmd
    - appendixC.qmd

appendix-style: default
search: true

bibliography: references.bib
csl: chicago-fullnote-bibliography-16th-edition.csl

format:
  html:
    theme:
      - pulse
      - hmsid.scss
    html-math-method: katex
    include-in-header:
      text: |
        <script defer data-domain="" src=""></script>
        <link rel = "shortcut icon" href = "favicon.ico" />
    code-overflow: wrap
    code-link: true
    code-copy: true
    fig-align: center
    fig-cap-location: bottom
    link-external-newwindow: true
    callout-appearance: simple
    author-meta: "Federica Gazzelloni"
    toc: true
    toc-title: Contents
    toc-location: right
    toc-depth: 3
    mermaid:
      theme: neutral

  pdf:
    documentclass: krantz
    classoption: [krantz2]
    keep-tex: true
    toc-title: Contents
    latex-output-dir: _book
    colorlinks: true
    fig-dpi: 300
    pdf-engine: xelatex
    include-in-header:
      - file: latex/preamble.tex
    include-before-body:
      - file: latex/before_body.tex
    include-after-body:
      - file: latex/after_body.tex
    bibliography: [references.bib]
    citation-style: chicago-fullnote-bibliography-16th-edition.csl

editor: visual
editor_options:
  chunk_output_type: inline

execute:
  echo: true
  message: false
  warning: false
  freeze: auto
  cache: false
  fig.align: 'center'
  dev: 'cairo_pdf'

tbl-cap-location: top
tbl-align: center

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"