project:
  type: book
  output-dir: _book

book:
  title: "Health Metrics and the Spread of Infectious Diseases"
  subtitle: "Machine Learning Applications and Spatial Modelling Analysis with R"
  author:
    name: Federica Gazzelloni
    orcid: 0000-0002-4285-611X
  date: "06/09/2023" # date of the agreement with the Editor
  publisher: "CRC Press - Chapman & Hall"
  publisher-place: "Boca Raton, FL."
  site-url: https://fgazzelloni.quarto.pub/hmsidr/
  repo-url: https://github.com/Fgazzelloni/hmsidR
  repo-branch: origin
  repo-actions: [edit, issue]
  sharing: [twitter, facebook, linkedin]
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-J9YVQPL7W9"
    anonymize-ip: true
  favicon: images/cover-canva.png
  cover-image: images/cover-canva.png
  cover-image-alt: "Cover image of the book Health Metrics and the Spread of Infectious Diseases"
  reader-mode: true
  sidebar:
    foreground: "primary"
    background: "#ebecf7"
    pinned: true
    style: docked
  page-footer:
    left: |
      &copy; 2024 This book is written by <a href="https://federicagazzelloni.netlify.app/">Federica Gazzelloni</a>.
    center: |
      Editor CRC Press - Chapman & Hall | Taylor & Francis Group
    right: |
      Built with ❤︎️ and [Quarto](https://quarto.org/)
    background: "#29306c"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "**Health Metrics**"
      chapters:
        - 01-health_metrics.qmd
        - 02-method_calculation.qmd
        - 03-components.qmd
        - 04-causes_risks.qmd
    - part: "**Machine Learning**"
      chapters:
        - 05-machine_learning.qmd
        - 06-techniques.qmd
        - 07-packages.qmd
        - 08-predictions.qmd
    - part: "**Data Visualization**"
      chapters:
        - 09-data_visualization.qmd
        - 10-applications.qmd
        - 11-spatials.qmd
        - 12-examples.qmd
    - part: "**Infectious Diseases**"
      chapters:
        - 13-infectious_diseases.qmd
        - 14-covid19.qmd
        - 15-malaria.qmd
        - 16-summary.qmd
    - conclusions.qmd
    - references.qmd
    - formulary.qmd
  appendices:
    - appendixA.qmd
    - appendixB.qmd
    - appendixC.qmd

appendix-style: default
bibliography: references.bib
csl: chicago-fullnote-bibliography-16th-edition.csl
crossref:
  lof-title: "List of Figures"
  lot-title: "List of Tables"

format:
  html:
    theme:
      - pulse
      - hmsid.scss
    html-math-method: katex
    include-in-header:
      text: |
        <script defer data-domain="" src=""></script>
        <link rel="shortcut icon" href="favicon.ico" />
    code-overflow: wrap
    code-link: true
    code-copy: true
    fig-align: center
    fig-cap-location: bottom
    link-external-newwindow: true
    callout-appearance: simple
    author-meta: "Federica Gazzelloni"
    toc: true
    toc-title: Contents
    toc-location: right
    toc-depth: 3
    mermaid:
      theme: neutral
  pdf:
    documentclass: krantz
    classoption: [krantz2]
    keep-tex: true
    toc-title: Contents
    latex-output-dir: _book
    colorlinks: true
    fig-dpi: 300
    pdf-engine: xelatex
    include-in-header:
      - file: latex/preamble.tex
    include-before-body:
      - file: latex/before_body.tex
    include-after-body:
      - file: latex/after_body.tex
    bibliography: [references.bib]
    citation-style: chicago-fullnote-bibliography-16th-edition.csl

editor: visual
editor_options:
  chunk_output_type: inline

execute:
  echo: true
  message: false
  warning: false
  freeze: auto
  cache: false
  fig.align: 'center'
  dev: 'cairo_pdf'

tbl-cap-location: top
tbl-align: center

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"